---
title: "Learning Reflection"
subtitle: "Week 6"
format:
  html:
    embed-resources: true
editor: visual
---

# Learning reflections

Learning reflections are part of your weekly homework and have a weight of 20% of your final grade. Write a reflection in your own words on the different parts of the weeks material below. You can also use your learning reflections as a notebook as you work through exercises or readings. Write as much as you like, but a minimum of 100 words in total.

# Lecture

\<n this lecture, I learned how to create and share dynamic reports using RStudio. We explored how to build and publish web-friendly documents with Quarto and GitHub Pages, making project results accessible online. I also discovered how to include references and link content like figures and tables within a document, enhancing clarity and professionalism. On the data side, we used tools from the dplyr package to combine data from different sources, an essential skill for working with complex datasets. The session helped me appreciate how RStudio supports both data analysis and effective communication of findings.\>

# Homework Assignment

\<Completing the homework that brought together all the R functions we have studied throughout the course gave me the opportunity to reinforce my understanding of key concepts. The practice improved my skills. By combining multiple functions in one task, I developed a deeper appreciation for how these tools work together to produce meaningful insights. This assignment helped build my confidence in applying R \>

# Readings

\<The chapter deepened my understanding of how data analysis often relies on multiple interconnected tables rather than a single dataset. It emphasized the importance of identifying primary and foreign keys to define relationships and introduced join operations such as mutating and filtering joins that allow merging or subsetting datasets effectively. I appreciated how the tools in R simplify operations with intuitive functions, enabling me to focus on analysis rather than complex syntax. Overall, this chapter enriched my ability to work with complex, relational data.\>

# Submit learning reflections

## Stage, Commit & Push to GitHub

This final section introduces the workflow you need to follow at the end of each live coding exercise, homework assignment, learning reflection. It ensures that all the changes you have made to files in this repository (folder) are synced with the version that is stored on GitHub. The steps will be described at the end of each of the files.

1.  Open the Git pane in RStudio. It's in the top right corner in a separate tab.
2.  **Stage** your changes by checking appropriate box next to all files (if you select one file with your mouse, you can then highlight them all with Ctrl + A on your keyboard and check all boxes)
3.  Write a meaningful commit message (e.g. "Completed week 6 learning reflection") in the **Commit message** box
4.  Click **Commit**. Note that every commit needs to have a commit message associated with it.
5.  Click **Push** to send your changes to GitHub.
6.  Go to your wk-06-USERNAME GitHub repo (where USERNAME is your GitHub username) and refresh the page. You should see your commit message next to the updated files.

## Open an issue on GitHub

Once you have ensured that the Quarto document renders without errors and you have pushed all your changes to GitHub, it is to complete the assignment by opening an issue on your wk-06-USERNAME GitHub repo (where USERNAME is your GitHub username).

1.  Navigate to your wk-06-USERNAME GitHub repo (where USERNAME is your GitHub username).
2.  Click on **Issues**, and then **New issue** button.
3.  Write a meaningful title in the **Title** field
4.  Tag the course instructor with using the `@` sign in combination with `larnsce` as the username
5.  Add any questions or comments
